metadata:
  title: Ihor Kalnytskyi
  author: Ihor Kalnytskyi
  url: https://kalnytskyi.com

pipes:
  compile:
    - name: import-processors
      args:
        imports:
          - guess-published-from-source = guess_published:process
          - alias = alias:process
        from_: _processors

    - name: source
      args:
        pattern: '[^_.].*$'

    - name: guess-published-from-source
      args:
        pattern: '(?P<trim>/(?P<parse>\d{4}-\d{2}-\d{2})_)'

    - name: pipe
      args:
        pipe:
          - name: frontmatter

          - name: commonmark
            args:
              pygmentize: true

          - name: archive
            when:
              - '"published" in item'
      when:
        - item.source.match("*.markdown")
        - item.source.parts[0] != "talks" or item.source.parts[1] == "index.markdown"

    - name: pipe
      args:
        pipe:
          - name: sitemap

          # Feed processor configuration is too overcomplicated now. Yet, it's
          # something we need anyway because its options reflect RSS/Atom
          # options. However, some sane defaults and references to metadata are
          # required and it's something Holocron will incorporate one day.
          - name: feed
            args:
              save_as: feed.xml
              feed:
                id:
                  $ref: metadata://#/url
                title:
                  $ref: metadata://#/title
                description: Ihor Kalnytskyi's thoughts & writings
                link:
                  - href: https://kalnytskyi.com/feed.xml
                    rel: self
                    type: application/atom+xml
                  - href:
                      $ref: metadata://#/url
                    rel: alternate
                    type: text/html
              item:
                id:
                  $ref: item://#/absurl
                title:
                  $ref: item://#/title
                content:
                  $ref: item://#/content
                link:
                  href:
                    $ref: item://#/absurl
                author:
                  name:
                    $ref: metadata://#/author
                published:
                  $ref: item://#/published
            when:
              - '"published" in item'
      when:
        - item.source.match("*.markdown")
        - item.source.parts[0] != "talks" or item.source.parts[1] == "index.markdown"

    - name: alias

    - name: jinja2
      args:
        themes: ["_theme"]
        context:
          theme:
            sidebar:
              photo: /about/me.jpg
              about: |
                <a href="/about/" rel="me">Ihor Kalnytskyi</a>'s thoughts & writings

            navigation: !!pairs
              - Archives: /
              - Talks: /talks/
              - Feed: /feed.xml

            twitter_cards:
              username: ikalnytskyi
      when:
        - |
          "template" in item or (
            item.source.match("*.markdown") and
            item.source.parts[0] != "talks" or item.source.parts[1] == "index.markdown"
          )

    - name: save
      args:
        to: "%(here)s/_site/"
