name: CD

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest

    services:
      graphviz:
        image: ghcr.io/ikalnytskyi/dot:latest
        options: --name graphviz --interactive
        credentials:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Set up dependencies
      run: |
        sudo apt install inkscape

        cat << EOF > /usr/local/bin/dot
        #!/bin/sh
        exec /usr/bin/docker exec --interactive graphviz /usr/bin/dot \$@
        EOF
        chmod +x /usr/local/bin/dot

        python -m pip install --upgrade pip
        python -m pip install --requirement requirements.txt

    - name: Run Holocron
      run: holocron run compile

    - name: Publish kalnytskyi.com
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
