name: CD

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Set up dependencies
      run: |
        sudo apt install inkscape

        python -m pip install --upgrade pip
        python -m pip install --requirement requirements.txt

    - name: Run Holocron
      run: holocron run compile

    - name: Publish kalnytskyi.com
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
