name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Set up dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --requirement requirements.txt

        # Because Ubuntu 20.04 still packages Inkscape < 1.0
        sudo wget https://inkscape.org/gallery/item/31669/Inkscape-0a00cf5-x86_64.AppImage -O /usr/bin/inkscape
        sudo chmod +x /usr/bin/inkscape

    - name: Run Holocron
      run: holocron run compile
