name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Set up dependencies
      run: |
        sudo apt install inkscape graphviz

        python -m pip install --upgrade pip
        python -m pip install --requirement requirements.txt

    - name: Run Holocron
      run: holocron run compile
